# vim: filetype=yaml
name: TPC Queries with Ibis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  tpc-queries-sqlite:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install python
        uses: actions/setup-python@v3
        id: install_python
        with:
          python-version: "3.10"

      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: ./runtpc -i sqlite -i ibis

  tpc-queries-duckdb:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install python
        uses: actions/setup-python@v3
        id: install_python
        with:
          python-version: "3.9"
          cache: "pip"

      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt
      - run: python -c "import duckdb; con = duckdb.connect('tpch.ddb'); con.execute('CALL dbgen(sf=0.1);')"
      - run: ./runtpc -i duckdb -i ibis -d 'tpch.ddb' -b 'duckdb'

  tpc-queries-substrait-duckdb:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install python
        uses: actions/setup-python@v3
        id: install_python
        with:
          python-version: "3.9"
          cache: "pip"

      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt
      - run: pip install --upgrade --pre duckdb
      - run: python -c "import duckdb; con = duckdb.connect('tpch.ddb'); con.execute('CALL dbgen(sf=0.1);')"
      - run: ./runtpc -i ibis -i substrait -d 'tpch.ddb' -b 'duckdb' || true

  ibis-substrait-duckdb-master:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install python
        uses: actions/setup-python@v3
        id: install_python
        with:
          python-version: "3.9"
          cache: "pip"

      - run: python -m pip install --upgrade pip pytest
      - run: pip install -r requirements.txt
      - run: pip uninstall -y ibis-framework
      - run: pip install --upgrade 'git+https://github.com/ibis-project/ibis.git@master'
      - run: pip install --upgrade --pre duckdb
      - run: PYTHONPATH=. pytest
